services:
  # run jupyter notebook inside jupyter 
  jupyter-notebook:
    image:  forsythiaolive/dsci522-2425-39-fmj:de8a9b6
    ports:
      - "8888:8888"
    volumes:
      - .:/home/jovyan
    deploy:
      resources:
        limits:
          memory: 5G
    platform: linux/amd64